-- Add Purchases and Suppliers tables
CREATE TABLE IF NOT EXISTS public.suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    address TEXT,
    email TEXT,
    balance NUMERIC DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.purchase_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "invoiceNumber" TEXT NOT NULL,
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "supplierId" BIGINT REFERENCES public.suppliers(id) ON DELETE SET NULL,
    "supplierName" TEXT NOT NULL,
    items JSONB NOT NULL,
    subtotal NUMERIC NOT NULL,
    discount NUMERIC DEFAULT 0,
    total NUMERIC NOT NULL,
    paid NUMERIC DEFAULT 0,
    remaining NUMERIC DEFAULT 0,
    "paymentStatus" TEXT DEFAULT 'unpaid',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Note: In Supabase table names and column names inside JSON objects must match the cases correctly when handled with select/update/insert.
-- By default supabase-js passes object keys directly, if they are camelCase like invoiceNumber, PostgreSQL requires double quotes to preserve case.
-- We created columns preserving camelCase to match the types directly.

-- Inform PostgREST to reload schema
NOTIFY pgrst, 'reload schema';
