CREATE TABLE IF NOT EXISTS public.shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cashier_id BIGINT REFERENCES public.users(id), -- Or UUID if you use auth.users
    opened_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    closed_at TIMESTAMP WITH TIME ZONE,
    status TEXT DEFAULT 'open',
    initial_cash NUMERIC DEFAULT 0,
    actual_cash NUMERIC DEFAULT 0,
    expected_cash NUMERIC DEFAULT 0,
    total_sales NUMERIC DEFAULT 0
);

-- Inform PostgREST to reload schema
NOTIFY pgrst, 'reload schema';
